### ISSUE TITLE
Reasonable inference...lol

### ISSUE THREAD

**Issue by KILjungjoon** [oddlyspaced/spotify-stuff#1]
It's a very interesting topic. I got a lot of inspiration from your work.
However, I wonder why you calculated the string similarity here.

Formulas are mathematically and statistically based on basic agreement, but are these formulas reliable?

Similarity Factor = (Count of Common Words between String1 and String2) / min(Count of Words in String1, Count of Words in String2)

Could the same pattern of similarity be captured not only in hip-hop but also in other genres?
I don't mean that this feature won't help you recognize trends in the genre.
Thank you.

**Comment by oddlyspaced** [comment]
Hey! Thanks a lot for showing interest in my little project lol

The main reason I chose to use string similarity over any other (and arguably more accurate) statistical measure was because I was having mixed feelings regarding the genre labels that Spotify added to the songs.

A lot of the genre labels were honestly misleading, and there were a lot of variations of the same genre (ex: indian pop, korean pop, japanese pop). I made the decision for string pattern matching mainly to generalize the genre's across the different songs thus, indian pop, korean pop, japanese pop would ultimately be grouped as a superset "pop".

This is not at all statistically reliable, since the labels themselves are not proper and have a high degree of variation. If we can possibly fetch the genre information from some other reliable source, while ensuring a much lesser degree of generalisation then that param would be much more statistically viable.
